# Generated by Django 3.1.1 on 2020-09-02 17:37

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='feedback',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mail', models.EmailField(max_length=254)),
                ('message', models.TextField()),
                ('timeStamp', models.DateTimeField(default=datetime.datetime(2020, 9, 2, 17, 37, 0, 536494, tzinfo=utc))),
            ],
        ),
    ]
